# Generated by Django 4.1.5 on 2023-03-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filmismi', models.CharField(max_length=200)),
                ('tur', models.CharField(max_length=100)),
                ('acıklama', models.TextField(max_length=600)),
                ('resim', models.FileField(blank=True, null=True, upload_to='afiş', verbose_name='afis')),
            ],
        ),
    ]
