# Generated by Django 4.1.5 on 2023-03-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_kategori_alter_movies_acıklama_alter_movies_filmismi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='tur',
        ),
        migrations.AddField(
            model_name='movies',
            name='tur',
            field=models.ManyToManyField(null=True, to='movies.tur'),
        ),
    ]
